DROP DATABASE UCASOFT;
CREATE DATABASE UCASOFT;



CREATE TABLE PROYECTO(
    codigo varchar(5) NOT NULL,
    denominacion varchar (30) NOT NULL,
    tipo varchar (30) NOT NULL,
    desc_txt VARCHAR(5),
    desc_doc VARCHAR(5),
    monto_acumulado int,
     url varchar(50),
     PRIMARY KEY (codigo)
);

CREATE TABLE CLIENTE(

    DUI VARCHAR (10) NOT NULL,
    DENOMINACION VARCHAR (40),
    TIPO VARCHAR (40),
    PRIMARY KEY (DUI)
);
CREATE TABLE MIEMBRO(
    DUI VARCHAR (10) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    DENOMINACION_DEPARTAMENTO VARCHAR(20),
    
    PRIMARY KEY (DUI)   
    --PROBABLE DE UTILIZAR ALTER TABLE PARA CREAR LA FOREIGN 
);

CREATE TABLE DEPARTAMENTO (
    DENOMINACION VARCHAR (10) NOT NULL,
    DUI_MIEMBRO_REPRESENTANTE VARCHAR(10),
    PRIMARY KEY (DENOMINACION),
    FOREIGN KEY (DUI_MIEMBRO_REPRESENTANTE) REFERENCES MIEMBRO(DUI)
);
ALTER TABLE MIEMBRO ADD  FOREIGN KEY (DENOMINACION_DEPARTAMENTO) 
        REFERENCES DEPARTAMENTO(DENOMINACION);
CREATE TABLE VERSION_PROYECTO(
    CODIGO_PROYECTO VARCHAR(5) NOT NULL,
    NUMERO FLOAT NOT NULL,
    DESCRIPCION VARCHAR(40) NULL,
    FK_PROYECTO_CODIGO VARCHAR(5),
    PRIMARY KEY(CODIGO_PROYECTO,NUMERO),
    FOREIGN KEY (FK_PROYECTO_CODIGO) REFERENCES PROYECTO (CODIGO)
);

CREATE TABLE SUPERPACHANGA(
    NOMBRE VARCHAR(50) UNIQUE NOT NULL,
    LEMA VARCHAR (20) NOT NULL,
    AÑO INT NOT NULL,
    PRIMARY KEY (NOMBRE)
);


CREATE TABLE ASISTE (

    NOMBRE_SUPERPACHANGA VARCHAR (40) NOT NULL,
    DUI_MIEMBRO VARCHAR(10) NOT NULL,
    PRIMARY KEY (NOMBRE_SUPERPACHANGA,DUI_MIEMBRO),
    FOREIGN KEY (NOMBRE_SUPERPACHANGA) REFERENCES SUPERPACHANGA(NOMBRE),
    FOREIGN KEY (DUI_MIEMBRO) REFERENCES MIEMBRO(DUI)

);

CREATE TABLE PROYECTO_PARTE(
    CODIGO_MACROPROYECTO VARCHAR(5) NOT NULL,
    CODIGO_SUBPROYECTO VARCHAR(5) NOT NULL,
    PRIMARY KEY (CODIGO_MACROPROYECTO,CODIGO_SUBPROYECTO),
    FOREIGN KEY (CODIGO_MACROPROYECTO) REFERENCES PROYECTO(CODIGO),
    FOREIGN KEY (CODIGO_SUBPROYECTO) REFERENCES PROYECTO(CODIGO) 
);


